### ISSUE TITLE
Get url up to query parameters

### ISSUE THREAD

**Issue by tanyona** [purge/youarei.js#10]
Is there a method to get the url string up to (excluding) the query parameters e.g for a url `http://user:pass@www.example.com:3000/a/b/c?d=dad&e=1&f=12.3` return `http://user:pass@www.example.com:3000/a/b/c`

**Comment by purge** [comment]
not exposed directly - you could concatenate scheme, user_info ,host, port and path of course but it might just be easier to do `source_url.split('?')[0]`
